# Generated by Django 3.1 on 2021-03-25 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='archive',
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_arch', to='travel.blog')),
            ],
        ),
    ]
