# Generated by Django 3.1 on 2021-03-27 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_search'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country']},
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
