# Generated by Django 3.1 on 2021-03-27 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20210327_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('How_many_people', models.IntegerField()),
                ('Choose_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='where', to='travel.country')),
                ('When_would_you_travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='travel.blog')),
            ],
        ),
    ]
