# Generated by Django 3.1 on 2021-03-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='When_would_you_travel',
            field=models.DateField(),
        ),
    ]
