# Generated by Django 3.1 on 2021-03-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20210327_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.CharField(max_length=200)),
                ('from_date', models.DateField()),
                ('till_date', models.DateField()),
                ('travelers', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='archive',
            options={'ordering': ['date']},
        ),
    ]
