# Generated by Django 3.1 on 2021-04-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_checkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
