# Generated by Django 3.1 on 2021-04-01 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='travelers',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='search',
            name='How_many_people',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
